### ISSUE TITLE
Unable to pull the image from dockerhub (HTTP Status: 530)

### ISSUE THREAD

**Issue by rajivvishwa** [scyto/docker-UnifiBrowser#14]
Getting an error while trying to pull the latest image. 

![image](https://user-images.githubusercontent.com/125708/197839179-8bc2ade8-0101-463f-aed0-dba6eec328dd.png)

**Comment by scyto** [comment]
I just tested and it works ok

530 would indicate you are having an issue with docker hub itself, not a lot i can do there to help
if you are using any form of ad-block or non standard dns  service on your network i recommend disabling and retesting
