### ISSUE TITLE
Docker update

### ISSUE THREAD

**Issue by SamKr** [scyto/docker-UnifiBrowser#16]
Hi @scyto,

Any chance you'll be able to update the docker image to the latest versions? In [the original issue I posted here](https://github.com/Art-of-WiFi/UniFi-API-browser/issues/114), @malle-pietje mentions that he'll try to update UniFi Browser to the latest API client. A bump in versions after that would be really great :)

Thanks for maintaining this!

**Comment by scyto** [comment]
Hi, I thought a container was now maintained inside the project? If not I can look at updating this one,

**Comment by SamKr** [comment]
Thanks for replying @scyto. The project's dev referred to you, so I don't think so: https://github.com/Art-of-WiFi/UniFi-API-browser/issues/114#issuecomment-2349371846 

Would be appreciated! If you want I can let you know here when @malle-pietje has updated it with the latest API client, to prevent having to do it twice?

**Comment by SamKr** [comment]
> I can let you know here when @malle-pietje has updated it with the latest API client, to prevent having to do it twice?

Update: he just did, so it's up to date already

**Comment by SamKr** [comment]
He just released a new version, any chance you could take a look at updating the docker container?

**Comment by scyto** [comment]
hmm, my memory is failing, thought i had done a PR to create this with github actions and do via main project, must have been one of my other containers in another project, lol.

let me see what i can do this week, i haven't looked at this in a long time so need some time to spin up and convert the process to using build actions in github, though i may spin a quick rev by hand if i can....

**Comment by SamKr** [comment]
No worries of course, sounds good! Thanks for taking the time to reply 👋

**Comment by scyto** [comment]
@SamKr  could you try this update (its not the latest but is more uptot date),  i want to test my build and push is working, use the test tag NOT latest tag

https://hub.docker.com/repository/docker/scyto/unifibrowser/general

this should be the chages phaeton proposed a PR for a few months ago, if this works I will update to latest latest code, then push to test again, if that works then i will publish to latest

(sorry i am slow, i am sick as dog with some type of cold)

**Comment by SamKr** [comment]
Tried the test container, however it keeps failing:

```
[+] Running 4/4
 ✔ unifiapibrowser Pulled                                                                                          4.7s
   ✔ 94c7366c1c30 Pull complete                                                                                    1.3s
   ✔ 7be095f5b0b5 Pull complete                                                                                    1.3s
   ✔ 5a6c748d75e1 Pull complete                                                                                    2.3s
[+] Running 2/2
 ✔ Network unifibrowsertest_default              Created                                                           0.2s
 ✔ Container unifibrowsertest-unifiapibrowser-1  Created                                                           0.5s
Attaching to unifiapibrowser-1
unifiapibrowser-1  | starting UniFi-API-browser
 does not exist.1  | Directory ./UniFi-API-browser
unifiapibrowser-1 exited with code 1
```

Seems like the folder isn't there after the git clone:

```
does not exist.1  | Directory ./UniFi-API-browser
```

> sorry i am slow, i am sick as dog with some type of cold

Just came off something too, and it seems everyone else in the country as well (NL), must be the time of the year 😁 Take your time, thanks for your effort and get well soon 👍

**Comment by scyto** [comment]
@SamKr can you try again, that got very weird (probably cause i am ill) it was odd because php started fine when i started container with -it and /bin/ash and rand the command in the script by hand

so i deconstructed the script and when I realized even cd /Unifi-API-Browser wasn't working in the script it was something weird

in reality something simple - somehow the script had been modified to use CRLF instead of LF - which is odd...

anyhoo reverted file to LF and it now PHP works, haven't looked to see if the app is working, could you verify this, then i will move on to updating to latest alpine too (this should actually be latest Unifi browser already as it just git clones )

**Comment by scyto** [comment]
closing as fixed, now works here, pushed to :latest

<img width="1273" alt="image" src="https://github.com/user-attachments/assets/a51ff1bf-c598-44a4-a5f2-078620221ca8">

**Comment by SamKr** [comment]
Hey @scyto, sorry for the late reply. Thanks for the effort, very nice find on that bug - those can be so nasty and take hours of your time while you start questioning your skills 😁 

Working like a charm ❤️
