### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by Unthred** [scyto/docker-UnifiBrowser#3]
OS - Unraid 6.8.2

I have the container running and have created a password using the link on your readme but whenever I try to login to the webpage I get 

starting UniFi-API-browser
PHP 7.3.11 Development Server started at Tue Feb 25 06:45:30 2020
[Tue Feb 25 06:46:01 2020] failed login attempt for user Squiggley

[Tue Feb 25 06:46:01 2020] 172.17.0.1:54320 [302]: /login.php
[Tue Feb 25 06:46:01 2020] 172.17.0.1:54324 [200]: /
[Tue Feb 25 06:46:01 2020] 172.17.0.1:54328 [200]: /css/custom.css?2.0.1
[Tue Feb 25 06:46:01 2020] 172.17.0.1:54332 [200]: /js/custom.js?2.0.1
[Tue Feb 25 06:46:02 2020] 172.17.0.1:54340 [200]: /ajax/fetch_sites.php
[Tue Feb 25 06:46:02 2020] 172.17.0.1:54344 [200]: /ajax/fetch_about_modal_metrics.php

Is it possible to get debug logging? I have tried a few different usernames and passwords I have also tried the ResetPHP Session as well

Thanks

**Comment by scyto** [comment]
What's interesting to me in that trace it appears to be trying to fetch sites - that happens after login.
As such I am wondering if this is the unifi username and pass word.  Does your unfi username or password have any special characters? also *if* you are using a UI to set the env vars check for spaces at the end or beginning of your envvars.  In terms of debugging you can shell into the container.

**Comment by scyto** [comment]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Unthred** [comment]
So I have just removed any special chars from both my unifi password and the one for your api browser. The passwords just have lowercase, uppercase and numbers in them now. Afraid it made no difference. I have also tried it directly ie bypassing my reverse proxy to see if that was the issue.
Will try again tonight and shell into the container see what I find

**Comment by scyto** [comment]
Hi, i had a friend with unraid set this up, it worked ok.
Could you paste (or DM me) the command that is being run by unraid, i suspect you have a typo with an envar, have confused which password to use where  or somesuch.

better yet would be an export of the template unraid created when you added my container in community apps UI, this article should help you locate it https://forums.unraid.net/topic/39285-where-on-flash-are-docker-templates-stored/

in terms of shell the shell is /bin/ash on this container

**Comment by Unthred** [comment]
Hi, sorry for the late reply been super busy. Thanks for your response. I wiped the container and config and started again and I now have it working. 

Thanks again!
