### ISSUE TITLE
Allow for no authentication

### ISSUE THREAD

**Issue by bdf0506** [scyto/docker-UnifiBrowser#5]
Can you make the docker container where if you pass a variable it will support NO auth? Seems like you can accomplish this by doing 
`-v <YourHostPath>/users.php:/UniFi-API-browser/config/users.php`

and then after the container starts, remove the file `<YourHostPath>/users.php`, but seems rather hacky. Would be nice if there is a variable that can be set to disable auth during the docker run process.

**Comment by scyto** [comment]
are you saying that removal of the users.php just turns off auth rather than breaking anything?

**Comment by scyto** [comment]
@bdf0506 not sure if you still use this but i have updated the container with this enhancement.

it is in `scyto/unifibrowser:noauth` you need to add a env var of ` -e NOAPIBROWSERAUTH=1` to your docker command line or whatever tool you use to spin up the container.

**Comment by scyto** [comment]
@bdf0506 i now have a test container with this working you need to pull the :test tag version and add a new env var called NOAPIBROWSERAUTH = 1 to disable auth, give it a go if you are still interested and then i can decide if i propagate to :latest or not (i think i might as i don't really like auth either on a read only service like this).

Or you can close the issue if you don't care any more :-)

**Comment by scyto** [comment]
closing as no feedback from OP in over 12mo
