### ISSUE TITLE
No sites available

### ISSUE THREAD

**Issue by VanadiumJade** [scyto/docker-UnifiBrowser#6]
Hi,

I have a UDM Pro, and i have pulled and run the docker as described. but no sites are available to pick from.
What am I doing wrong?

**Comment by scyto** [comment]
Usually mean the port was wrong, or so version is wrong.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by VanadiumJade** [comment]
this is what I used:
docker run --name unifiapi -p:8000:8000 -e USER=unifiLocalUser -e PASSWORD=unifiLocalPassword -e UNIFIURL=https://192.168.1.1 -e PORT=443 -e APIBROWSERPASS=a_long_number scyto/unifibrowser

IP is 192.168.1.1... based on its being a UDM pro I set to 443.

any ideas what I could be doing wrong. inside the same network. no fancy networking rules.

UDM Pro version: 1.8.0
Network controller version: 5.14.22

**Comment by trendelkamp** [comment]
Same issue for me, with the same setup as @VanadiumJade

**Comment by scyto** [comment]
I can take a look today and see if i have same issue, sorry this open issue passed me by in Nov, not sure why.

**Comment by scyto** [comment]
@trendelkamp  would you mind sending me your exactly command line.  Also can you make your secrets only have basic alpha numeric with optionally ! symbol (no other symbols or spaces or special European characters).  also can you try running NOT on the UDMP (install docker desktop if you don't have other docker engine)

I just pulled the image fresh and created a container and it worked perfectly:

![image](https://user-images.githubusercontent.com/11369180/104822139-4fa8d200-57f5-11eb-99ae-8c56a13724b2.png)
 these are my vars
![image](https://user-images.githubusercontent.com/11369180/104822153-6818ec80-57f5-11eb-8583-c7b8019a4503.png)

**Comment by scyto** [comment]
i also uploaded an updated version that uses latest version  of unifi browser to the :test tag you could give that a go incase there is a bug in the underlying Unifi browser code

**Comment by scyto** [comment]
also make sure you set the user up correctly on the unif - like this one:

![image](https://user-images.githubusercontent.com/11369180/104822465-88e24180-57f7-11eb-957b-064dce568505.png)

**Comment by trendelkamp** [comment]
@scyto running now. Stupid me, URL ENV was ending with a / ... Removed that and its working fine now. Thanks!

**Comment by scyto** [comment]
@trendelkamp awesome, glad you solved it.

Could you test the :test version, then i can promote that to :latest too so we have whatever updates were made in the last 9mo or whatever since i last did a push :-)

**Comment by jonesalexr** [comment]
> 
> 
> @trendelkamp awesome, glad you solved it.
> 
> Could you test the :test version, then i can promote that to :latest too so we have whatever updates were made in the last 9mo or whatever since i last did a push :-)

The test and noauth tags dont work for me. I am able to use the latest fine. I have tested on two Pi's in docker. They all install fine, but on the test version, it cant get through to the controller.

**Comment by scyto** [comment]
I have no idea what state test and no auth tags are in, I will remove them.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by scyto** [comment]
> > @trendelkamp awesome, glad you solved it.
> > Could you test the :test version, then i can promote that to :latest too so we have whatever updates were made in the last 9mo or whatever since i last did a push :-)
> 
> The test and noauth tags dont work for me. I am able to use the latest fine. I have tested on two Pi's in docker. They all install fine, but on the test version, it cant get through to the controller.

Jan 16 was an eternity ago.  I just checked, my noauth tag build and it worked not sure why it didn't for you unless you send me you compose or command line.

I squashed it into latest and repushed make sure you set all the env fields documented.

If it doesn't see a controller the usual culprit is wrong URL (don't put trailing / ) port or unifi username and password.
Are you using UDM/UDMP or classic controller, I haven't tried with classic controller.

**Comment by scyto** [comment]
i just updated to 2.0.17 see if that helps you (repull the image)

**Comment by jonesalexr** [comment]
Latest update broke it. Have it running on two different pi's.
**Working Copy Below**
UniFi API Browser version
    2.0.8 bleeding edge! 
PHP API client version
    1.1.49
Controller URL
    https://192.168.1.1:443
Controller user name
    APIExplorer
Controller version
    6.1.52
PHP version
    7.3.15
PHP memory_limit
    128M
peak PHP memory used
    1.31M
cURL version
    7.67.0
OpenSSL version
    OpenSSL/1.1.1d
operating system
    Linux 5.10.11-v7l+ 

**Broken latest version Below**
UniFi API Browser version
    2.0.17 up to date 
PHP API client version
    1.1.66
Controller URL
    https://192.168.1.1:443
Controller user name
    APIExplorer
Controller version
    not detected
PHP version
    7.4.15
PHP memory_limit
    128MB
peak PHP memory used
    1.39MB
cURL version
    7.74.0
OpenSSL version
    OpenSSL/1.1.1j
operating system
    Linux 5.4.83-v7l+ 

**Docker inspect below (both match as all i changed was the tag.)**

`pi@raspberrypi14:~ $ docker inspect  UnifiExplorer14
[
    {
        "Id": "9e49ff2fe38596f4ff951781395e7dfb99c3cd8a7d3e622bc31af0f44554f0f7"                                                                                                                                                             ,
        "Created": "2021-02-21T03:56:08.289967481Z",
        "Path": "sh",
        "Args": [
            "./start.sh"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 11814,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2021-02-21T03:56:18.208238732Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:7e783f51b7af8b1f7fee0e1dd337334f70dff559ccbf8a553d11c75                                                                                                                                                             664871f27",
        "ResolvConfPath": "/var/lib/docker/containers/9e49ff2fe38596f4ff95178139                                                                                                                                                             5e7dfb99c3cd8a7d3e622bc31af0f44554f0f7/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/9e49ff2fe38596f4ff951781395e                                                                                                                                                             7dfb99c3cd8a7d3e622bc31af0f44554f0f7/hostname",
        "HostsPath": "/var/lib/docker/containers/9e49ff2fe38596f4ff951781395e7df                                                                                                                                                             b99c3cd8a7d3e622bc31af0f44554f0f7/hosts",
        "LogPath": "/var/lib/docker/containers/9e49ff2fe38596f4ff951781395e7dfb9                                                                                                                                                             9c3cd8a7d3e622bc31af0f44554f0f7/9e49ff2fe38596f4ff951781395e7dfb99c3cd8a7d3e622b                                                                                                                                                             c31af0f44554f0f7-json.log",
        "Name": "/UnifiExplorer14",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "bridge",
            "PortBindings": {
                "8000/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8000"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": [
                "AUDIT_WRITE",
                "CHOWN",
                "DAC_OVERRIDE",
                "FOWNER",
                "FSETID",
                "KILL",
                "MKNOD",
                "NET_BIND_SERVICE",
                "NET_RAW",
                "SETFCAP",
                "SETGID",
                "SETPCAP",
                "SETUID",
                "SYS_CHROOT"
            ],
            "CapDrop": [
                "AUDIT_CONTROL",
                "BLOCK_SUSPEND",
                "DAC_READ_SEARCH",
                "IPC_LOCK",
                "IPC_OWNER",
                "LEASE",
                "LINUX_IMMUTABLE",
                "MAC_ADMIN",
                "MAC_OVERRIDE",
                "NET_ADMIN",
                "NET_BROADCAST",
                "SYSLOG",
                "SYS_ADMIN",
                "SYS_BOOT",
                "SYS_MODULE",
                "SYS_NICE",
                "SYS_PACCT",
                "SYS_PTRACE",
                "SYS_RAWIO",
                "SYS_RESOURCE",
                "SYS_TIME",
                "SYS_TTY_CONFIG",
                "WAKE_ALARM"
            ],
            "CgroupnsMode": "host",
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ],
            "Init": false
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/43a1459291e3ed6fa6c52571e0                                                                                                                                                             828ecdc7bfc7cafc41a7bfa527c1070923a1d7-init/diff:/var/lib/docker/overlay2/e2c427                                                                                                                                                             117e4cd6ff839bf3b6886ce601b8aefb228fa223fb05eca647a657bd97/diff:/var/lib/docker/                                                                                                                                                             overlay2/effa50895669a3e2c0ae503a8feeabd9891cfb74d95860223b121cd94518bd59/diff:/                                                                                                                                                             var/lib/docker/overlay2/a9503b24dec9bae70e56c9e018488d432a2724cfb12b58c8ff0f0848                                                                                                                                                             b45ec5b1/diff",
                "MergedDir": "/var/lib/docker/overlay2/43a1459291e3ed6fa6c52571e                                                                                                                                                             0828ecdc7bfc7cafc41a7bfa527c1070923a1d7/merged",
                "UpperDir": "/var/lib/docker/overlay2/43a1459291e3ed6fa6c52571e0                                                                                                                                                             828ecdc7bfc7cafc41a7bfa527c1070923a1d7/diff",
                "WorkDir": "/var/lib/docker/overlay2/43a1459291e3ed6fa6c52571e08                                                                                                                                                             28ecdc7bfc7cafc41a7bfa527c1070923a1d7/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "196b17705495",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "USER=APIExplorer",
                "PASSWORD=Noneyourbusiness",
                "UNIFIURL=https://192.168.1.1",
                "DISPLAYNAME=default",
                "APIBROWSERUSER=admin",
                "APIBROWSERPASS=thishasbeenchanged",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/b                                                                                                                                                             in",
                "LANG=C.UTF-8",
                "TZ=America/Los_Angeles",
                "PORT=443",
                "NOAPIBROWSERAUTH=0"
            ],
            "Cmd": [
                "sh",
                "./start.sh"
            ],
            "Image": "scyto/unifibrowser:latest",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "7424cd51181cfd95210e201e723f3ba10421b147593fcbd79b12c3                                                                                                                                                             04cbcd200c",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "8000/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8000"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/7424cd51181c",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "dbc0bfa43cc0ebee8f8944859f68b409cdf7a356347905b41eddc                                                                                                                                                             e50622fd328",
            "Gateway": "178.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "178.17.0.5",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "macwuzhere",
            "Networks": {
                "bridge": {
                    "IPAMConfig": {},
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "9409f251c51e90294be1939e641bb8e992b131f482cd59                                                                                                                                                             7c2bf6fa2ac674b7eb",
                    "EndpointID": "dbc0bfa43cc0ebee8f8944859f68b409cdf7a35634790                                                                                                                                                             5b41eddce50622fd328",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.5",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "macwuzhere",
                    "DriverOpts": null
                }
            }
        }
    }
]
`

**Comment by scyto** [comment]
I also have an issue on a pi, but on my x86 based docker host (a synology) it is working perfectly.  Trying to figure out why...

~~1. on the pi can you run it not detached and show me any error message you see in the console 
2. are you able to test in on x86 based linux host~~

**Comment by scyto** [comment]
this is some weird shit!  there is some interaction between pi docker and alpine images that utterly screws time and date.
this goes beyond a TZ issue as the container thinks it is 2071 - which makes all the 443 certs invalid, which is why the container can't figure it out.

Options:
1) i can move the container to debian:buster-slim but this will double or triple the size of the image (made a :buster tag you can try instead, let me know if that works)
2) keep banging my head against the time issue  (and no it isn't as simple as install TZ data)

look at the time and year - makes no sense.

```
[Sun Jul  5 16:45:20 2071] 192.168.1.108:64237 Closing
[Sun Jul  5 16:47:04 2071] 192.168.1.108:64327 Accepted
[Sun Jul  5 16:47:04 2071] 192.168.1.108:64328 Accepted
[Sun Jul  5 14:01:04 2071] The $users array in the config/users.php file does not exist or is empty, proceeding without user authentication.
[Sun Jul  5 16:36:32 2071] 192.168.1.108:64327 [200]: GET /
[Sun Jul  5 16:45:20 2071] 192.168.1.108:64327 Closing
[Sun Jul  5 13:55:28 2071] PHP Notice:  cURL error: Failed to connect to 192.168.1.1 port 443: Operation timed out in /UniFi-API-browser/vendor/art-of-wifi/unifi-api-client/src/Client.php on line 155
[Sun Jul  5 13:55:28 2071] PHP Notice:  cURL error: Failed to connect to 192.168.1.1 port 443: Operation timed out in /UniFi-API-browser/vendor/art-of-wifi/unifi-api-client/src/Client.php on line 186
[Sun Jul  5 16:36:32 2071] 192.168.1.108:64328 [200]: POST /ajax/fetch_sites.php
[Sun Jul  5 16:45:20 2071] 192.168.1.108:64328 Closing
[Sun Jul  5 16:47:04 2071] 192.168.1.108:64336 Accepted
[Sun Jul  5 16:36:32 2071] 192.168.1.108:64336 [200]: GET /ajax/fetch_about_modal_metrics.php
[Sun Jul  5 16:45:20 2071] 192.168.1.108:64336 Closing
```

**Comment by scyto** [comment]
@jonesalexr  seems it was a breaking change in alpine https://stackoverflow.com/questions/66091978/corrupt-date-with-redis6-alpine-on-raspi

until Raspbian is updated to use a new version of libseccomp2 all containers built with alpine:latest (3.13) will fail in weird ways due to time being borked.

i hard set version of alpine to 3.12 and should be good now

**Comment by jonesalexr** [comment]
I confirm the latest image works great! good work! What an odd error to not push a bugfix for!

**Comment by scyto** [comment]
> I confirm the latest image works great! good work! What an odd error to not push a bugfix for!

i only push changes when folks ask for a change to the image on dockerhub
closing
