### ISSUE TITLE
Error loading sites or no sites available (via Docker)

### ISSUE THREAD

**Issue by nodecentral** [scyto/docker-UnifiBrowser#8]
Hi

I have a UniFi cloudkey gen2 , USG 3, various switches and ports and I’m looking for some help on the following issues which is driving me crazy..

I’ve followed the instructions and really thought I was there , environment variables are below..
````
"TZ=Europe/London", 
"USER=vera", 
"PASSWORD=vera", 
"PORT=8443", 
"UNIFIURL=https://192.168.22.207", 
"DISPLAYNAME=NodeCentral", 
"APIBROWSERPASS=c7ad44cbad762a5da0a452f9e854fdc1e0e7a52a38015f23f3eab1d80b931dd472634dfac71cd34ebc35d16ab7fb8a90c81f975113d6c7538dc69dd8de9077ec"
````

but the error below still comes up..

![85B35874-6AB8-43A9-8C5A-E763D79B3EA3](https://user-images.githubusercontent.com/4349292/116832219-bf2bad00-abab-11eb-88ba-21c298492ed2.jpeg)

**Comment by nodecentral** [comment]
Hi, 

It seems the issue was the port number, I followed the guidance on the Docker site https://github.com/scyto/docker-UnifiBrowser that said to use 8443  ‘ _Port if you changed the port unifi is running on - default env var setting 443 is now the default for UDM / UDMP for older UniFiOS based controllers change to 8443 controllers_’ - as I do not have a UDM .

Seems it’s just 443 for my UniFiOS set up too.

**Comment by scyto** [comment]
What version was your controller software?
I didn't know they had rolled out the new stuff to older CKs, nice to know, thanks!
I will think about how to update the docs.

**Comment by nodecentral** [comment]
Looks like I’m on 6.10.0
